name: eyesFreeCV
channels:
- conda-forge
- https://conda.binstar.org/menpo
- menpo
- anaconda-fusion
- defaults
dependencies:
- x264=20131217=3
- cycler=0.10.0=py27_0
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- icu=54.1=0
- libpng=1.6.27=0
- matplotlib=2.0.2=np112py27_0
- mkl=2017.0.1=0
- numpy=1.12.1=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=2
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- opencv=2.4.11=py27_1
- tbb=4.3_20141023=0
- ffmpeg=2.8.6=0
